### PR TITLE
Retrieving the error message from response in login

### LINKED ISSUE #555: Retrieve the error message of login request
Retrofit android library expect a mapped object from a request even when the status code is different than 200. On login endpoint it is an User object, but serve return a not mapped json object `{error: "Invalid Email or password."}`

### PR DESCRIPTION
**Pull request by amiapmorais**
fix #555 

- [ ] **Model testing.**
- [ ] **Request testing and swagger doc update.**
- [ ] **System testing.**
- [x] **No tests required.**

### CODE REVIEW

File: android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt [hunk 1]
```diff
@@ -58,19 +58,23 @@ class LoginActivity : AppCompatActivity() {
...
-                        sessionManager.storeData(API_TOKEN, it)
+                    if (response.isSuccessful) {
+                        response.body()?.let {
+                            storeLoginData(it)
+                            openMainActivity()
+                        }
+                        response.headers()["Authorization"]?.let {
+                            sessionManager.storeData(API_TOKEN, it)
+                        }
+                    } else{
```
Comment (iurynogueira) [inline android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt:69]:
```suggestion
                    } else {
```

File: android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt [hunk 2]
```diff
@@ -58,19 +58,23 @@ class LoginActivity : AppCompatActivity() {
...
+                        response.errorBody()?.let {
+                            val jsonResponse = JSONObject(it.string())
+                            Toast.makeText(applicationContext, jsonResponse.getString("error"), Toast.LENGTH_LONG)
+                                .show()
+                            Log.d("TAG_", jsonResponse.getString("error"))
```
Comment (iurynogueira) [inline android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt:74]:
```suggestion
```

File: android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt [hunk 3]
```diff
@@ -58,19 +58,23 @@ class LoginActivity : AppCompatActivity() {
...
+                            openMainActivity()
+                        }
+                        response.headers()["Authorization"]?.let {
+                            sessionManager.storeData(API_TOKEN, it)
+                        }
+                    } else{
+                        response.errorBody()?.let {
+                            val jsonResponse = JSONObject(it.string())
+                            Toast.makeText(applicationContext, jsonResponse.getString("error"), Toast.LENGTH_LONG)
+                                .show()
```
Comment (iurynogueira) [inline android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt:73]: I Belive that this will be implements in many places, is considerable implement a function to this?

**Review by iurynogueira — CHANGES_REQUESTED** [review]
We need tests 💔

File: android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt (hunk 1 above)
Comment (amiapmorais) [reply android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt:69]: done

File: android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt (hunk 2 above)
Comment (amiapmorais) [reply android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt:74]: I forgot to remove this line. Thanks

File: android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt (hunk 3 above)
Comment (amiapmorais) [reply android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginActivity.kt]: I moved the error response check to the API layer, removing it from the view layer.

**Review by iurynogueira — APPROVED** [review]
