### PR TITLE
🎨 Fix responsive grid options

### LINKED ISSUE #579: Improve responsive layout alignment for question
There is no spacing between buttons and right side
image

### PR DESCRIPTION
**Pull request by iurynogueira**
fix #579

### CODE REVIEW

**Review by andersonmalheiro — APPROVED** [review]

File: frontend/src/components/survey-item/survey-item.tsx [hunk 1]
```diff
@@ -45,9 +45,15 @@ export const SurveyItem = (props: SurveyItemProps) => {
 
   const randomImage = () => {
     const images = [
-      'https://ik.imagekit.io/u7kjueyghmd/question_card_template1_tDW_SAGUh.jpg',
-      'https://ik.imagekit.io/u7kjueyghmd/question_card_template3_otkvluVvys.jpeg',
-      'https://ik.imagekit.io/u7kjueyghmd/question_card_template2_ku8ufHjdpCYW.jpeg',
+      'https://images.pexels.com/photos/7103/writing-' +
```
Comment (edimossilva) [inline frontend/src/components/survey-item/survey-item.tsx:48]: Why not use images from imagekit?

**Review by edimossilva — APPROVED** [review]

**Review by edimossilva — APPROVED** [review]
Amazing!
